# Generated by Django 6.0 on 2025-12-05 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leasing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre del Método"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "Nacional"),
                            ("INTERNATIONAL", "Internacional"),
                            ("LOCAL", "Local (Entrega/Recogida)"),
                        ],
                        default="NATIONAL",
                        max_length=20,
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Costo Base",
                    ),
                ),
                (
                    "cost_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Costo por Kg (Opcional)",
                    ),
                ),
                (
                    "estimated_delivery_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Días Estimados"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Número de Seguimiento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("SHIPPED", "Enviado"),
                            ("IN_TRANSIT", "En Tránsito"),
                            ("DELIVERED", "Entregado"),
                            ("RETURNED", "Devuelto"),
                            ("SCHEDULED_PICKUP", "Programado para Recogida"),
                            ("PICKED_UP", "Recogido"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "origin_address",
                    models.TextField(verbose_name="Dirección de Origen"),
                ),
                (
                    "destination_address",
                    models.TextField(verbose_name="Dirección de Destino"),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha Programada (Entrega/Recogida)",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="Nombre Cliente"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Email Cliente"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="leasing.rentalcontract",
                        verbose_name="Contrato Relacionado",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shipping.shippingmethod",
                        verbose_name="Método de Envío",
                    ),
                ),
            ],
        ),
    ]
