# Generated by Django 6.0 on 2025-12-04 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SaleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la Categoría",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="products.salecategory",
                        verbose_name="Categoría Padre",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categorías de Venta",
            },
        ),
        migrations.CreateModel(
            name="SaleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Producto"
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Marca"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="Modelo"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Descripción y Características"),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código SKU"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio de Venta"
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(default=0, verbose_name="Stock Disponible"),
                ),
                (
                    "custom_attributes",
                    models.JSONField(
                        default=dict,
                        help_text="Atributos específicos del producto (e.g., {'Tipo Conector': 'HDMI', 'Velocidad': '10Gbps'})",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.salecategory",
                        verbose_name="Categoría",
                    ),
                ),
            ],
        ),
    ]
