# Generated by Django 6.0 on 2025-12-04 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Categoría de Arrendamiento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categorías de Arrendamiento",
            },
        ),
        migrations.CreateModel(
            name="RentalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del Equipo"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Descripción y Especificaciones"),
                ),
                (
                    "specifications",
                    models.JSONField(
                        default=dict,
                        help_text="Detalles técnicos (e.g., {'RAM': '16GB', 'Procesador': 'i7'})",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código de Inventario"
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad en Inventario para Arrendamiento",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_products",
                        to="leasing.rentalcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diario"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensual"),
                            ("ANNUAL", "Anual"),
                        ],
                        max_length=10,
                        verbose_name="Periodo",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio Base por Periodo",
                    ),
                ),
                (
                    "maintenance_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Costo Adicional de Mantenimiento/Seguro",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="leasing.rentalproduct",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Planes de Arrendamiento",
                "unique_together": {("product", "period")},
            },
        ),
        migrations.CreateModel(
            name="RentalContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de Finalización")),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "is_signed",
                    models.BooleanField(default=False, verbose_name="Contrato Firmado"),
                ),
                (
                    "contract_document",
                    models.TextField(
                        verbose_name="Términos y Condiciones del Contrato (Aplicados)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente de Pago/Firma"),
                            ("ACTIVE", "Activo"),
                            ("COMPLETED", "Completado"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Estado del Contrato",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="leasing.rentalplan",
                        verbose_name="Plan de Arrendamiento",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="leasing.rentalproduct",
                        verbose_name="Equipo Arrendado",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contratos de Arrendamiento",
            },
        ),
    ]
